name: Pull Request
description: Create a report to help me improve
body:
- type: checkboxes
  attributes:
    label: Prerequirement
    options:
      - label: "I use to most recent version of [`Turabian 9th Dutch`](https://github.com/Ignotum77/Turabian-9th-Dutch/blob/main/turabian-9th-edition-full-note.csl)"
        required: true

- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true

- type: textarea
  attributes:
    label: To Reproduce
    description: "Steps to reproduce the behavior:"
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Screenshot
    description: If applicable, add screenshots to help explain your problem.
    value: |
      <details>
      <summary>Screenshot(s)</summary>
      
      <!-- Put your screenshot(s) here -->
      
      </details>
  validations:
    required: false

- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the problem here.
  validations:
    required: false
